### ISSUE TITLE
Kitchen suites

### ISSUE THREAD

**Issue by iennae** [criteo-cookbooks/reposync#1]
If you define suites in the kitchen.yml file, and leave the section out of the other kitchen configurations you have then you'll get equivalent of what you are trying to do without using erubis.

**Comment by jmauro** [comment]
Hello @iennae,

The only issue: this suite won't be tested when using ec2 kitchen, that's why we have created a common file for kitchen vagrant and ec2. 

Regards,
Jeremy MAURO
