### ISSUE TITLE
Allow sync of metadata

### ISSUE THREAD

**Issue by emo3** [criteo-cookbooks/reposync#3]
You should allow for:
--downloadcomps --download-metadata
options to the reposync command

**Comment by jmauro** [comment]
Hello @emo3,

It was possible to give command line arguments but the resource was not explicitly exposing this property. The next release will provide this feature.

Regards,
JM

**Comment by jmauro** [comment]
hello @emo3, you can now use any options you want with version 0.1.2 (cf: https://github.com/criteo-cookbooks/reposync/commit/5e62a6e62ff9d611d1eb5c01cf375212f4416d4d)

Regards,
JM
